### PR TITLE
Rahma

### PR DESCRIPTION
**Pull request by imahnama**
Shopping_list UI HTML,CSS and just in mind.

### CODE REVIEW

**Comment by ghost** [comment]
The design is good. I like how it's minimalistic.
Some of the things I would change would be:
* the color of these text on the login page, "We'll never share your email with anyone else."
It's not visible
* The background photo on the login page is a bit blurred.

**Comment by imahnama** [comment]
hello @Stankim 
Thank you for your review...point noted will change the issues

**Comment by jimmykimani** [comment]
Lets name the pr according to these conventions https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices

**Comment by imahnama** [comment]
@jimmykimani 
okay .Thanks

**Pull request merged**
